name: CI Checks

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: "Clangd install"
        run: sudo apt install clang-format
      - name: "Clangd format"
        run: git ls-files -z '*.c' | xargs -0 clang-format --dry-run --Werror
      - name: "Download submodules"
        run: git submodule update --init --recursive
      - name: Install zig 
        uses: mlugg/setup-zig@v2
        with:
          version: 0.16.0
      - name: Install build dependencies
        run: >
          sudo apt-get update &&
          sudo apt-get install -y
          libasound2-dev libgl1-mesa-dev libglu1-mesa-dev
          libwayland-dev libxkbcommon-dev libegl-dev
          wayland-protocols pkg-config
      - name: Cleanup cache folders
        continue-on-error: true
        run: |
          set -x  # enable shell tracing (shows every command)
          echo "ZIG_GLOBAL_CACHE_DIR=${ZIG_GLOBAL_CACHE_DIR}"
          echo "ZIG_LOCAL_CACHE_DIR=${ZIG_LOCAL_CACHE_DIR}"
          rm -rfv "$ZIG_GLOBAL_CACHE_DIR" || true
          rm -rfv "$ZIG_LOCAL_CACHE_DIR" || true
          set +x
      - name: Unit tests
        run: zig build -j1 test
      - name: Build project 
        run: zig build --summary all -j1 --color off -freference-trace=0 -Doptimize=ReleaseSafe --verbose

